In [3]:

# @hidden_cell
# This connection object is used to access your data and contains your credentials.
# You might want to remove those credentials before you share your notebook.

from project_lib import Project
project = Project.access()
Covid_19_cases_by_states_credentials = project.get_connected_data(name="Covid-19 cases by states")

import jaydebeapi, pandas as pd
Covid_19_cases_by_states_connection = jaydebeapi.connect('com.ibm.db2.jcc.DB2Driver',
    '{}://{}:{}/{}:user={};password={};'.format('jdbc:db2',
    Covid_19_cases_by_states_credentials['host'],
    '50000',
    Covid_19_cases_by_states_credentials['database'],
    Covid_19_cases_by_states_credentials['username'],
    Covid_19_cases_by_states_credentials['password']))

query = 'SELECT * FROM HQF66087.COVID19_STATES'
data_df_1 = pd.read_sql(query, con=Covid_19_cases_by_states_connection)
data_df_1.head()

# You can close the database connection with the following code.
# Covid_19_cases_by_states_connection.close()
# To learn more about the jaydebeapi package, please read the documentation: https://pypi.org/project/JayDeBeApi/

         date       state  fips  cases  deaths
0  2020-01-21  Washington    53      1       0
1  2020-01-22  Washington    53      1       0
2  2020-01-23  Washington    53      1       0
3  2020-01-24    Illinois    17      1       0
4  2020-01-24  Washington    53      1       0